### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by pranavavva** [takari/polyglot-maven-examples#7]
Like the title suggests, I don't actually have a bug to report, just wanted to know something: The same tags used in `pom.xml` can be used in `pom.yml` right? For example, 

```xml
<manifest>
    <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
    <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
    <mainClass>my.pacakge.App</mainClass>
    <packageName>my.package</packageName>
</manifest>
```

becomes

```yml
manifest:
  addDefaultImplementationEntries: true
  add DefaultSpecificationEntries: true
  mainClass: my.package.App
  packageName: my.package
```
